# Exercício 009 - Tabuada
n = int(input("Digite um número para ver a tabuada: "))

print('-'*15)
print('{} x {:.2f} = {}'.format(n,1,n*1))
print('{} x {:.2f} = {}'.format(n,2,n*2))
print('{} x {:.2f} = {}'.format(n,3,n*3))
print('{} x {:.2f} = {}'.format(n,4,n*4))
print('{} x {:.2f} = {}'.format(n,5,n*5))
print('{} x {:.2f} = {}'.format(n,6,n*6))
print('{} x {:.2f} = {}'.format(n,7,n*7))
print('{} x {:.2f} = {}'.format(n,8,n*8))
print('{} x {:.2f} = {}'.format(n,9,n*9))
print('{} x {:.2f} = {}'.format(n,10,n*10))
print('-'*15)